---
apiVersion: kustomize.toolkit.fluxcd.io/v1alpha1
kind: Kustomization
metadata:
  creationTimestamp: null
  name: webapp
  namespace: gitops-system
spec:
  healthChecks:
  - kind: Deployment
    name: frontend
    namespace: production
  - kind: Deployment
    name: backend
    namespace: production
  interval: 10m0s
  path: ./deploy/overlays/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: webapp
  timeout: 2m0s
  validation: client
status: {}

